name: Link Checker

on:
  schedule:
  - cron: 0 0 1 * *
  pull_request:
    branches:
    - master

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.1
      with:
        args: -v -r *